[package]
name = "libindy"
version = "1.9.0"
authors = [
  "Sergej Pupykin <sergej.pupykin@dsr-company.com>",
  "Vyacheslav Gudkov <vyacheslav.gudkov@dsr-company.com>",
  "Artem Ivanov <artem.ivanov@dsr-company.com>",
  "Evgeniy Razinkov <evgeniy.razinkov@dsr-company.com.ru>",
  "Kirill Neznamov <kirill.neznamov@dsr-company.com>",
  "Sergey Minaev <sergey.minaev@dsr-company.com>"
  ]

description = "This is the official SDK for Hyperledger Indy (https://www.hyperledger.org/projects), which provides a distributed-ledger-based foundation for self-sovereign identity (https://sovrin.org). The major artifact of the SDK is a c-callable library."
license = "MIT/Apache-2.0"
build = "build.rs"

[lib]
name = "indy"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
default = ["bn_openssl", "ed25519_sign_sodium", "ed25519_box_sodium", "sealedbox_sodium", "base58_rust_base58", "base64_rust_base64", "xsalsa20_sodium", "chacha20poly1305_ietf_sodium", "pair_amcl", "hash_openssl", "local_nodes_pool", "revocation_tests", "pwhash_argon2i13_sodium", "hmacsha256_sodium", "memzero_sodium", "randombytes_sodium"]
bn_openssl = ["openssl", "int_traits"]
ed25519_sign_sodium = ["sodiumoxide"]
ed25519_box_sodium = ["sodiumoxide"]
sealedbox_sodium = ["sodiumoxide"]
base58_rust_base58 = ["rust-base58"]
base64_rust_base64 = ["base64"]
xsalsa20_sodium = ["sodiumoxide"]
chacha20poly1305_ietf_sodium = ["sodiumoxide"]
pwhash_argon2i13_sodium = ["sodiumoxide"]
pair_amcl = ["ursa"]
hash_openssl = ["openssl"]
local_nodes_pool = []
revocation_tests = []
force_full_interaction_tests = []
sodium_static = []
hmacsha256_sodium = ["sodiumoxide"]
memzero_sodium = ["sodiumoxide"]
randombytes_sodium = ["sodiumoxide"]

# Causes the build to fail on all warnings
fatal_warnings = []

[dependencies]
mongodb = { path = "./mongo-rust-driver-prototype" }
int_traits = { version = "=0.1.1", optional = true }
digest = "=0.7.6"
env_logger = "=0.5.13"
errno = "=0.2.4"
etcommon-rlp = "=0.2.5"
failure = "=0.1.5"
generic-array = "=0.9.0"
hex = "=0.2.0"
libc = "=0.2.41"
log = { version = "=0.4.8", features = ["std"] }
log-derive = "=0.3.2"
derivative = "=1.0.3"
dirs = "=1.0.5"
openssl = { version = "=0.10.12", optional = true }
owning_ref = "=0.3.3"
rand = "=0.6.5"
rusqlite = "=0.13.0" # Make sure rusqlite for android is also bumped with this. Rusqlite for android is at the bottom of this document.
libsqlite3-sys = "=0.9.3"
rust-base58 = {version = "=0.0.4", optional = true}
base64 = {version = "=0.10.1", optional = true}
serde = "=1.0.104"
serde_json = "=1.0.44"
serde_derive = "=1.0.104"
sha2 = "=0.7.1"
sha3 = "=0.7.3"
rmp-serde = "=0.13.7"
sodiumoxide = {version = "=0.0.16", optional = true}
time = "=0.1.42"
threadpool = "=1.7.1"
zmq = "=0.8.3"
lazy_static = "=1.4.0"
named_type = "=0.1.6"
named_type_derive = "=0.1.6"
byteorder = "=1.3.2"
log-panics = "=2.0.0"
zeroize = "=0.5.2"
ursa = { version = "=0.1.1", optional = true }
ed25519-dalek = "=1.0.0-pre.1"
curve25519-dalek = "=1.2.2"
grpcio = "=0.4.7"
protobuf = "=2.8.1"
futures = "=0.1.29"

[dependencies.uuid]
version = "=0.7.4"
default-features = false
features = ["v4"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "=0.5.3"
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
rusqlite = { version = "=0.13.0", features=["bundled"] }

[dev-dependencies]
criterion = "=0.2.11"
indy = { path = "../wrappers/rust", version = "=1.9.0" }
indy-sys = { path = "../wrappers/rust/indy-sys", version = "=1.9.0" }
futures = "=0.1.29"
mockall = "0.6.0"

[[bench]]
name = "wallet"
harness = false
